### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by niklassc-xyz** [SOSETH/docker#1]
Der VSETH braucht docker-compose. Ist es besser wenn wir das in dieser Rolle hinzufügen, oder als seperate Rolle erstellen?

**Comment by uubk** [comment]
Prinzipell kannst du es in dieser Rolle installieren - einfach eine Variable `docker_install_compose` hinzufügen die auf `False` defaulted und es dann darüber steuern. Der Grund warum es bisher nicht drin ist ist dass wir das meistens für irgeneine Software gebraucht haben, die eh noch Config brauchte, und dann halt dafür für die jeweilige Software eine Rolle gebaut und das dadrin installiert haben.
